[package]
name = "wishget"
version = "0.1.0"
edition = "2021"

[profile.release]
lto = true
strip = true
opt-level = 3

[dependencies]
clap = { version = "4.3.2", features = ["derive"] }
reqwest = { version = "0.11.18", features = ["blocking"] }

anyhow = "1.0"
serde_json = "1.0"

open = "4.1.0"
