[package]
name = "wishget"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rust-strings = "0.4.0"
open = "4.0.0"
clap = "4.2.5"
glob = "0.3.1"
regex = "1"
url = { version = "2", features = ["serde"] }
json = "0.12.4"
reqwest = { version = "0.11.18", features = ["blocking"] }